### ISSUE TITLE
Crashes with AttributeError: type object 'IOLoop' has no attribute 'initialized'

### ISSUE THREAD

**Issue by alexgleith** [mapbox/rio-glui#30]
I can't get this to work with a fresh install on Mac OS.

Version follow:

- Python3:`3.6.5`
- pip: `10.0.1`
- rio: `1.0.0`

I tried installing tornado, as suggested elsewhere, but it already is installed. Also installed `pymq` but that didn't have any affect.

Error follows:

```
rio glui https://oin-hotosm.s3.amazonaws.com/5ac626e091b5310010e0d482/0/5ac626e091b5310010e0d483.tif
Inspecting https://oin-hotosm.s3.amazonaws.com/5ac626e091b5310010e0d482/0/5ac626e091b5310010e0d483.tif at http://127.0.0.1:8080/index.html
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/rio", line 11, in <module>
    sys.exit(main_group())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rio_glui/scripts/cli.py", line 128, in glui
    app.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rio_glui/server.py", line 125, in start
    is_running = IOLoop.initialized()
AttributeError: type object 'IOLoop' has no attribute 'initialized'
```

**Comment by vincentsarago** [comment]
👋 Hi @alexgleith can you check https://github.com/mapbox/rio-glui/issues/29
 and make sure you have `tornado==4.5.3`

**Comment by alexgleith** [comment]
That fixed it, @vincentsarago! Thanks ;-)
